version: "3.3"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "30001:80"
      - "30002:443"
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
      - "./config/my.cnf:/etc/mysql/my.cnf"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
    ports:
      - "5000:80"
    volumes:
      - "./config/config.inc.php:/etc/phpmyadmin/config.inc.php"
volumes:
  mysql-data:
